version: "3.4"
services:
  worker:
    image: riot/murdock-worker:latest
    init: true
    tmpfs:
       - /tmp:exec,size=${MURDOCK_BUILD_TMPFS_GIGS}g,rw
    volumes:
      - ccache:/cache/.ccache
      - gitcache:/cache/.gitcache
      - ./scripts/murdock-worker.sh:/murdock-worker.sh
    environment:
      - CCACHE="ccache"
      - CCACHE_DIR=/cache/.ccache
      - CCACHE_MAXSIZE=${MURDOCK_CCACHE_MAXSIZE_GIGS:-8}G
      - CCACHE_COMPRESS=true
      # each file takes at least 4kb, so this needs to match the max size
      # default to `0` (unlimited)
      - CCACHE_MAX_FILES=${MURDOCK_CCACHE_MAX_FILES:-0}
      - GIT_CACHE_DIR=/cache/.gitcache
      - MURDOCK_HOSTNAME=${MURDOCK_HOSTNAME}
      - MURDOCK_REDIS_HOST=ssh_bridge
      - JOBS=${MURDOCK_JOBS:-4}
      - DWQ_DISQUE_URL=ssh_bridge:7711
    user: "999"
    entrypoint:
      - /murdock-worker.sh
    command: dwqw --name ${MURDOCK_HOSTNAME} --queues ${MURDOCK_HOSTNAME} ${MURDOCK_QUEUES:-defaultx} --jobs ${MURDOCK_WORKERS:-2} --verbose

    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.centurylinklabs.watchtower.scope=murdock-worker-${MURDOCK_HOSTNAME}

  ssh_bridge:
    # any image that has autossh+ssh would do, but we're pulling
    # `murdock-worker:latest` anyways.
    image: riot/murdock-worker:latest
    volumes:
       - ./ssh:/root/.ssh
    command: >-
     /usr/bin/autossh
      -M 0 -C -N -o ServerAliveInterval=60 -o ServerAliveCountMax=2
      -Lssh_bridge:7711:${MURDOCK_REMOTE_DISQUE_HOST_PORT:-disque:7711}
      -Lssh_bridge:6379:${MURDOCK_REMOTE_REDIS_HOST_PORT:-redis:6379}
      murdock
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.centurylinklabs.watchtower.scope=murdock-worker-${MURDOCK_HOSTNAME}

  cache-keepalive:
      # this is used to keep the cache volume alive during restarts of the other
      # service containers (e.g., when docker compose recreates them after a pull.)
      # if the last container using a tmpfs volume unmounts it, the tmpfs
      # contents are gone. So, use a dummy container that's just using the
      # volume
      # Also, fixup cache folder permissions.
      image: alpine:latest
      init: true
      volumes:
        - ccache:/cache/.ccache
        - gitcache:/cache/.gitcache
      command: sh -c 'trap "exit" INT TERM KILL; chown 999 /cache/.ccache /cache/.gitcache ; while true; do sleep 1 ; done'
      restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_SCOPE=murdock-worker-${MURDOCK_HOSTNAME}
    command: --label-enable

volumes:
  ccache:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: exec,rw,noatime,size=${MURDOCK_CCACHE_MAXSIZE_GIGS:-8}g
  gitcache:
